apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      imagePullPolicy: Never
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "pivotal"
      ports:
        - containerPort: 3306
